---

- name: Check if toolboxrc is needed
  raw: stat $HOME/.toolboxrc
  register: need_bootstrap
  ignore_errors: True
  changed_when: False
  failed_when: False
  when: force is not defined

- name: Run bootstrap.sh
  script: "bootstrap.sh {{ force }}"
  when: force is defined or need_bootstrap | failed
  register: result
